name: Backend CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Backend/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-backend

jobs:
  test-backend:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    # Tests se ejecutan SIEMPRE (en PR y en push)
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mysqli, pdo, pdo_mysql, zip

      - name: Install Composer dependencies
        run: |
          cd Backend
          composer install --dev

      - name: Run PHPUnit tests
        run: |
          cd Backend
          vendor/bin/phpunit tests

  build-and-push-backend:
    name: Build and Push Backend Image
    runs-on: ubuntu-latest
    needs: test-backend  # Solo ejecuta si los tests pasan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Solo en push a main, no en PR

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set short git commit SHA
        id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        env:
          SHORT_SHA: ${{ steps.commit.outputs.short }}
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            ${{ steps.commit.outputs.short }}
            latest

      - name: Build, tag and push Backend Docker image
        env:
          IMAGE_TAG: ${{ steps.commit.outputs.short }}
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          dockerfile: ./Backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
